# When to start alerting staff of ignores on a player (0 to disable)
alert_threshold: 3


# Cross-server messaging and mail
server_name: null

redis:
  enabled: false
  server: localhost
  password: null
  timeout: 3000
  port: 6379
  max_connections: 4

mysql:
  enabled: false
  url: "jdbc:mysql://localhost:3306/mail"
  username: archer
  password: guest
  max_connections: 5


# Messages of the day
MOTD: ''
MBMOTD: ''
ABMOTD: ''
